### ISSUE TITLE
SelectedNote is not being picked up by NoteEditor

### ISSUE THREAD

**Issue by GyulizH** [GyulizH/notAl#2]
Eventhough the selected note is updated on the store when an item from the notelist is clicked, the selected note is not being picked up by note editor.

**Comment by kucukkanat** [comment]
Please refer to https://github.com/GyulizH/notAl/commit/797a6e17dc612310f8dc6f80f5fcfad3a921d8b6 for a possible fix. 
See what you have been missing, complete and open a PR to be reviewed.

**Comment by GyulizH** [comment]
the issue is resolved.
